In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import sqlite3
from scipy.stats import ttest_ind
import scipy.stats as stats
warnings.filterwarnings('ignore')

# loading the dataset

In [6]:
#creating db connection bro
conn=sqlite3.connect('inventory.db')

#fetching the data bro
df=pd.read_sql_query('select * from vendor_sales_summary',conn)
df.head()

,VendorNumber,VendorName,Brand,Description,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,36.99,1750.0,145080,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,28.99,1750.0,164038,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,24.99,1750.0,187407,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,22.99,1750.0,201682,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,29.99,1750.0,138109,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

# EDA
WE ANALYZE THE RESULTANT TABLE TO GAIN INSIGHTS INTO DISTRIBUTION OF EACH COLUMN AND METRIC
    helps us understand 
    -data patterns
    -identify anomalies
    -data quality 
    for further analysis

In [8]:
#summary statistics
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,10682,10683,10684,10685,10686,10687,10688,10689,10690,10691
VendorNumber,1128,4425,17035,3960,3960,480,17035,3960,3960,12546,...,4425,6785,90024,3960,3960,9815,8004,3924,3960,7245
VendorName,BROWN-FORMAN CORP,MARTIGNETTI COMPANIES,PERNOD RICARD USA,DIAGEO NORTH AMERICA INC,DIAGEO NORTH AMERICA INC,BACARDI USA INC,PERNOD RICARD USA,DIAGEO NORTH AMERICA INC,DIAGEO NORTH AMERICA INC,JIM BEAM BRANDS COMPANY,...,MARTIGNETTI COMPANIES,PALM BAY INTERNATIONAL INC,VINILANDIA USA,DIAGEO NORTH AMERICA INC,DIAGEO NORTH AMERICA INC,WINE GROUP INC,SAZERAC CO INC,HEAVEN HILL DISTILLERIES,DIAGEO NORTH AMERICA INC,PROXIMO SPIRITS INC.
Brand,1233,3405,8068,4261,3545,3858,2589,3102,3489,1376,...,27934,22161,46135,8729,2626,8527,5683,9123,6127,3065
Description,Jack Daniels No 7 Black,Tito's Handmade Vodka,Absolut 80 Proof,Capt Morgan Spiced Rum,Ketel One Vodka,Grey Goose Vodka,Jameson Irish Whiskey,Smirnoff Traveler,Tanqueray,Jim Beam,...,Terruzzi & Puthod Vernaccia,Santa Rita Organic Svgn Bl,Aresti Pnt Nr Curico Vly,Smirnoff Light Strawberry,Crown Royal Apple,Concannon Glen Ellen Wh Zin,Dr McGillicuddy's Apple Pie,Deep Eddy Vodka,The Club Strawbry Margarita,Three Olives Grape Vodka
ActualPrice,36.99,28.99,24.99,22.99,29.99,23.99,39.99,17.99,27.99,21.99,...,4.99,4.99,10.99,0.99,1.99,4.99,0.49,0.99,1.99,0.99
Volume,1750.0,1750.0,1750.0,1750.0,1750.0,750.0,1750.0,1750.0,1750.0,1750.0,...,750.0,750.0,750.0,50.0,50.0,750.0,50.0,50.0,200.0,50.0
TotalPurchaseQuantity,145080,164038,187407,201682,138109,138809,70783,161386,91835,108866,...,1,1,1,4,2,2,6,2,1,1
TotalPurchaseDollars,3811251.6,3804041.22,3418303.68,3261197.94,3023206.01,2466635.93,2177285.08,2088334.84,1903739.55,1773427.14,...,3.37,3.35,3.28,2.96,2.84,2.64,2.34,1.48,1.47,0.71
TotalSalesQuantity,142049.0,160247.0,187140.0,200412.0,135838.0,141860.0,69627.0,148265.0,90481.0,107061.0,...,1.0,1.0,19.0,6.0,14.0,5.0,134.0,2.0,72.0,86.0
TotalSalesDollars,5101919.510001,4819073.49,4538120.6,4475972.88,4223107.62,3383912.400001,2773367.73,2592041.35,2640491.19,2435393.39,...,4.99,9.99,94.81,5.94,27.86,15.95,65.66,1.98,143.28,85.14
TotalSalesPrice,672819.31,561512.37,461140.15,420050.01,545778.28,446932.09,614529.34,292586.29,503661.02,426902.78,...,4.99,9.99,59.88,2.97,5.97,10.96,1.47,0.99,77.61,33.66
TotalExciseTax,260999.2,294438.66,343854.07,368242.8,249587.83,111699.19,127931.67,272422.6,166244.44,196707.35,...,0.11,0.11,2.12,0.31,0.73,0.55,7.04,0.1,15.12,4.46
FreightCost,68601.68,144929.24,123780.22,257032.07,257032.07,89286.27,123780.22,257032.07,257032.07,123880.97,...,144929.24,13605.41,2802.64,257032.07,257032.07,27100.41,50293.62,14069.87,257032.07,38994.78
GrossProfit,1290667.91,1015032.27,1119816.92,1214774.94,1199901.61,917276.47,596082.65,503706.51,736751.64,661966.25,...,1.62,6.64,91.53,2.98,25.02,13.31,63.32,0.5,141.81,84.43
ProfitMargin,25.297693,21.06281,24.675786,27.139908,28.412764,27.10698,21.493098,19.432812,27.902068,27.181081,...,32.46493,66.466466,96.540449,50.16835,89.806174,83.448276,96.436186,25.252525,98.974037,99.166079
StockTurnover,0.979108,0.97689,0.998575,0.993703,0.983556,1.02198,0.983668,0.918698,0.985256,0.98342,...,1.0,1.0,19.0,1.5,7.0,2.5,22.333333,1.0,72.0,86.0
SalesToPurchaseRatio,1.338647,1.26683,1.327594,1.372493,1.396897,1.371873,1.273773,1.2412,1.387002,1.373269,...,1.480712,2.98209,28.905488,2.006757,9.809859,6.041667,28.059829,1.337838,97.469388,119.915493